import Head from 'next/head'
import React from 'react'

const Header = () => {
  return (
    <div>
    <Head>
    <title>AndGoEdu Blog</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head></div>
  )
}

export default Header